---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # The Managers (Flux Controllers)
  - infrastructure.yaml
  - apps.yaml
  # Foundational Resources (No controller manages these, so we do it here)
  - infrastructure/namespaces/