---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infrastructure.yaml
  - ./apps.yaml
  - ./infrastructure/gateway/
  - ./infrastructure/namespaces/
  - ./apps/aws-load-balancer-controller
  - ./apps/podinfo/
  - ./apps/envoy-gateway/