apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize # path within the git repo to deploy from
  prune: true # garbage collection, anything deleted in git will be deleted in cluster
  sourceRef: # refer to gitrepo in the other file, podinfo-repo.yaml
    kind: GitRepository
    name: podinfo
  targetNamespace: default
