apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
  namespace: default
spec:
  parentRefs:
    - name: external-gateway
      namespace: flux-system
  rules:
    - backendRefs:
        - name: podinfo
          port: 9898